export type TourStepPosition = "top" | "bottom" | "left" | "right";

export interface TourStep {
  id: string;
  portal: "manager" | "worker" | "client" | "admin";
  path: string;
  /** CSS selector for the element to highlight. null = center-screen message */
  selector: string | null;
  title: string;
  body: string;
  position: TourStepPosition;
}

export const PORTAL_COLORS: Record<string, string> = {
  manager: "#1d4ed8",
  worker: "#059669",
  client: "#b45309",
  admin: "#7c3aed",
};

export const TOUR_STEPS: TourStep[] = [
  {
    id: "mgr-kpis",
    portal: "manager",
    path: "/dashboard",
    selector: "[data-tour='kpi-row']",
    title: "Command Center",
    body: "Real-time KPIs across all your sites \u2014 open tickets, active tasks, compliance scores, and active workers at a glance.",
    position: "bottom",
  },
  {
    id: "mgr-tickets-table",
    portal: "manager",
    path: "/dashboard",
    selector: "[data-tour='recent-tickets']",
    title: "Recent Tickets",
    body: "Latest tickets from the field, prioritized and actionable. Click any ticket to see full details.",
    position: "top",
  },
  {
    id: "mgr-sites",
    portal: "manager",
    path: "/dashboard/sites",
    selector: "[data-tour='sites-list']",
    title: "Site Management",
    body: "All your sites in one view with quality scores and compliance status.",
    position: "bottom",
  },
  {
    id: "mgr-compliance",
    portal: "manager",
    path: "/dashboard/compliance",
    selector: "[data-tour='compliance-overview']",
    title: "Compliance Dashboard",
    body: "Track vendor compliance against industry standards \u2014 APPA, ISSA, Skytrax, Joint Commission, and more.",
    position: "bottom",
  },
  {
    id: "mgr-ticket-board",
    portal: "manager",
    path: "/dashboard/tickets",
    selector: "[data-tour='ticket-board']",
    title: "Ticket Lifecycle",
    body: "Full ticket management from creation to resolution. Filter by status, priority, site, or assignee.",
    position: "bottom",
  },
  {
    id: "mgr-people",
    portal: "manager",
    path: "/dashboard/people",
    selector: "[data-tour='people-list']",
    title: "Team Management",
    body: "Your team \u2014 managers, workers, and their role assignments. Invite new members or adjust permissions.",
    position: "bottom",
  },
  {
    id: "mgr-gates",
    portal: "manager",
    path: "/dashboard/gates",
    selector: "[data-tour='gates-view']",
    title: "Gate Operations",
    body: "Gate-level operations for airport clients. See occupancy, cleaning windows, and task assignments per gate.",
    position: "bottom",
  },
  {
    id: "mgr-live",
    portal: "manager",
    path: "/dashboard/live",
    selector: "[data-tour='live-map']",
    title: "Live Tracking",
    body: "Real-time worker locations across your sites. See who\u2019s on-site, active tasks, and movement history.",
    position: "bottom",
  },
  {
    id: "worker-tasks",
    portal: "worker",
    path: "/worker",
    selector: "[data-tour='worker-tasks']",
    title: "Worker Task View",
    body: "Workers see today\u2019s assigned cleaning tasks in a mobile-first layout. Start and complete tasks with one tap.",
    position: "bottom",
  },
  {
    id: "worker-nav",
    portal: "worker",
    path: "/worker",
    selector: "[data-tour='worker-nav']",
    title: "Simple Navigation",
    body: "Three tabs \u2014 Tasks, Tickets, and Map. Designed for field workers on mobile devices.",
    position: "top",
  },
  {
    id: "worker-map",
    portal: "worker",
    path: "/worker/map",
    selector: "[data-tour='worker-map']",
    title: "Worker Route Map",
    body: "Interactive map showing assigned task locations and optimal routes.",
    position: "bottom",
  },
  {
    id: "client-quality",
    portal: "client",
    path: "/client-portal",
    selector: "[data-tour='quality-score']",
    title: "Quality Score",
    body: "Clients see their overall quality score front and center \u2014 independent verification of vendor performance.",
    position: "bottom",
  },
  {
    id: "client-sites",
    portal: "client",
    path: "/client-portal",
    selector: "[data-tour='site-performance']",
    title: "Site Performance",
    body: "Performance breakdown by site with trend indicators. Drill into any site for detailed metrics.",
    position: "top",
  },
  {
    id: "client-compliance",
    portal: "client",
    path: "/client-portal/compliance",
    selector: "[data-tour='client-compliance']",
    title: "Compliance Scoring",
    body: "Independent compliance scoring against industry frameworks. See how every vendor measures up.",
    position: "bottom",
  },
  {
    id: "client-map",
    portal: "client",
    path: "/client-portal/map",
    selector: "[data-tour='client-map']",
    title: "Site Map",
    body: "Geographic view of all client sites with quality indicators and quick access to site details.",
    position: "bottom",
  },
  {
    id: "admin-users",
    portal: "admin",
    path: "/admin/users",
    selector: "[data-tour='admin-users']",
    title: "User Management",
    body: "Manage users, roles, and permissions across the organization. Invite new members or adjust access.",
    position: "bottom",
  },
  {
    id: "admin-settings",
    portal: "admin",
    path: "/admin/settings",
    selector: "[data-tour='admin-settings']",
    title: "Organization Settings",
    body: "Configure your organization \u2014 locale, session timeout, branding, and feature flags.",
    position: "bottom",
  },
  {
    id: "admin-integrations",
    portal: "admin",
    path: "/admin/integrations",
    selector: "[data-tour='admin-integrations']",
    title: "Integrations",
    body: "Connect external systems \u2014 flight data providers, access control, HR systems, and more.",
    position: "bottom",
  },
  {
    id: "mgr-sidebar",
    portal: "manager",
    path: "/dashboard",
    selector: "[data-tour='sidebar-nav']",
    title: "Contextual Navigation",
    body: "Every portal has role-appropriate navigation. Managers see operations tools, clients see quality metrics, workers see tasks.",
    position: "right",
  },
  {
    id: "tour-end",
    portal: "manager",
    path: "/dashboard",
    selector: null,
    title: "That\u2019s IQS Flow",
    body: "Independent quality oversight for organizations managing cleaning services. Any questions?",
    position: "bottom",
  },
];
